[theme]
base = "light"
primaryColor = "#2962FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#000000"

[server]
headless = true
runOnSave = true
enableCORS = false
port = 8501

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
server.headless = true

